spring:
  config.import: optional:secret.yaml
  application:
    name: todoapp
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: ${client_id}
            client_secret: ${client_secret}

logging:
  level:
    ROOT: DEBUG


server:
  port: 9090
